# Generated by Django 5.1.2 on 2024-10-21 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_cohortgroup_students_alter_program_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortgroup',
            name='students',
            field=models.ManyToManyField(to='students.student'),
        ),
        migrations.AlterField(
            model_name='program',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
